title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://thisispurefm.github.io/tech-docs

# site logo
logo: "/assets/site-logo.png"

# favicon
favicon_ico: "/assets/favicon.ico"
