title: PureFM Technical Documentation
description: The Portsmouth University Radio Experiences technical documentation
remote_theme: just-the-docs/just-the-docs

url: https://thisispurefm.github.io/tech-docs

color_scheme: dark

# site logo
logo: "/assets/site-logo.png"

# favicon
favicon_ico: "/assets/favicon.ico"

# Footer customisation
last_edit_timestamp: true
last_edit_time_format: "%Y-%m-%d %T"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/thisispurefm/tech-docs"

# callouts
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red