title: PureFM Technical Documentation
description: The Portsmouth University Radio Experiences technical documentation
remote_theme: just-the-docs/just-the-docs

url: https://thisispurefm.github.io/tech-docs

# site logo
logo: "/assets/site-logo.png"

# favicon
favicon_ico: "/assets/favicon.ico"
